Q1. Write a program to distinguish between Array Indexing and Fancy Indexing.

In [1]:
#Write a program to distinguish between Array Indexing and Fancy Indexing.
import numpy as np

# Array Indexing
arr = np.array([1, 2, 3, 4, 5])
print("Array Indexing:")
print(arr[0])
print(arr[1:3])

# Fancy Indexing
print("\nFancy Indexing:")
arr = np.array([1, 2, 3, 4, 5])
indices = np.array([0, 2, 3])
print(arr[indices])


Array Indexing:
1
[2 3]

Fancy Indexing:
[1 3 4]


Q2. Execute the 2D array Slicing.

In [2]:
#Execute the 2D array Slicing.
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Slice the array to get the first two rows and columns
subarray1 = arr[:2, :2]

# Slice the array to get the last two rows and columns
subarray2 = arr[1:, 2:]

# Print the subarrays
print("First Two Rows and Columns:\n", subarray1)
print("Last Two Rows and Columns:\n", subarray2)

First Two Rows and Columns:
 [[1 2]
 [5 6]]
Last Two Rows and Columns:
 [[ 7  8]
 [11 12]]


Q3. Create the 5-Dimensional arrays using ‘ndmin’.

In [3]:
#5d array
import numpy as np

# Create a 5D array with ndmin
arr = np.array([1, 2, 3, 4], ndmin=5)

# Print the array and its shape
print("Array:\n", arr)
print("Shape of Array:", arr.shape)

Array:
 [[[[[1 2 3 4]]]]]
Shape of Array: (1, 1, 1, 1, 4)


Q4. Reshape the array from 1-D to 2-D array.

In [4]:
#Reshape the array from 1-D to 2-D array.
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array to a 2D array with 2 rows and 3 columns
arr_2d = np.reshape(arr, (2, 3))

# Print the original and reshaped arrays
print("Original Array:\n", arr)
print("Reshaped Array:\n", arr_2d)

Original Array:
 [1 2 3 4 5 6]
Reshaped Array:
 [[1 2 3]
 [4 5 6]]


Q5. Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack().

In [5]:
#Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack().
import numpy as np

# Create two 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Stack them using stack()
print("Stack():")
print(np.stack((arr1, arr2), axis=0))

# Stack them using hstack()
print("\nhstack():")
print(np.hstack((arr1, arr2)))

# Stack them using vstack()
print("\nvstack():")
print(np.vstack((arr1, arr2)))

# Stack them using dstack()
print("\ndstack():")
print(np.dstack((arr1, arr2)))

Stack():
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

hstack():
[[1 2 5 6]
 [3 4 7 8]]

vstack():
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

dstack():
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


Q6. Perform the searchsort method in Numpy array.

In [6]:
#Perform the searchsort method in Numpy array.
import numpy as np

# Create a sorted array
arr = np.array([1, 2, 3, 4, 5])

# Find the index where 3 should be inserted
index = np.searchsorted(arr, 3)

# Print the index
print("Index of 3:", index)

Index of 3: 2


Q7. Create Numpy Structured array using your domain features.

In [27]:
#Create Numpy Structured array using your domain features.
#railways management system
import numpy as np

# Define the data types for the fields
dt = np.dtype([('flightname', 'U10'), ('train-id', 'i4'), ('destination', 'U10')])

# Create a structured array with 2 records
arr = np.array([('Emirates', 1425, 'London'), ('Spicejet', 1730, 'bangalore')], dtype=dt)

# Print the structured array
print(arr)

[('Emirates', 1425, 'London') ('Spicejet', 1730, 'bangalore')]


In [12]:
#Create Data frame using List and Dictionary.
import pandas as pd

# Define the data as a list of dictionaries
data = [{'name': 'kalpana', 'age': 20, 'gender': 'F'},
        {'name': 'likitha', 'age': 30, 'gender': 'F'},
        {'name': 'vikram', 'age': 45, 'gender': 'M'}]

# Create the DataFrame
df = pd.DataFrame(data)

# Print the DataFrame
print(df)

      name  age gender
0  kalpana   20      F
1  likitha   30      F
2   vikram   45      M


In [14]:
#Create Data frame on your Domain
import pandas as pd
import numpy as np

# Create a dictionary with missing values
data = {'flight_no': [1, 2, np.nan, 3],
        'flight_name': ['Emirates', 'Indigo', np.nan, 'Vistara'],
        'source': ['Delhi', 'Mumbai', np.nan, 'Kolkata'],
        'destination': ['Chennai', 'Bangalore', np.nan, 'Hyderabad'],
        'departure_time': [np.nan, '10:00', '12:00', '14:00'],
        'arrival_time': ['08:00', np.nan, '14:00', '18:00']}

# Create the DataFrame
df = pd.DataFrame(data)

# Check for missing values using isnull()
print("Missing Values:\n", df.isnull())

# Check for non-missing values using notnull()
print("\nNon-Missing Values:\n", df.notnull())

# Drop rows with missing values using dropna()
df_dropped = df.dropna()
print("\nDataFrame after dropping rows with missing values:\n", df_dropped)

# Fill missing values using fillna()
df_filled = df.fillna(0)
print("\nDataFrame after filling missing values with 0:\n", df_filled)

# Replace missing values using replace()
df_replaced = df.replace(np.nan, -1)
print("\nDataFrame after replacing missing values with -1:\n", df_replaced)

# Interpolate missing values using interpolate()
df_interpolated = df.interpolate()
print("\nDataFrame after interpolating missing values:\n", df_interpolated)

Missing Values:
    flight_no  flight_name  source  destination  departure_time  arrival_time
0      False        False   False        False            True         False
1      False        False   False        False           False          True
2       True         True    True         True           False         False
3      False        False   False        False           False         False

Non-Missing Values:
    flight_no  flight_name  source  destination  departure_time  arrival_time
0       True         True    True         True           False          True
1       True         True    True         True            True         False
2      False        False   False        False            True          True
3       True         True    True         True            True          True

DataFrame after dropping rows with missing values:
    flight_no flight_name   source destination departure_time arrival_time
3        3.0     Vistara  Kolkata   Hyderabad          14:00    

In [16]:
#Perform the Hierarchical Indexing in the above created dataset.
import pandas as pd

# Create a dictionary with data
data = {'flight_no': [121, 122,123, 124],
        'flight_name': ['Emirates', 'Indigo', 'Vistara', 'Air india'],
        'source': ['Delhi', 'Mumbai', 'Kolkata', 'Chennai'],
        'destination': ['Chennai', 'Bangalore', 'Hyderabad', 'Mumbai'],
        'departure_time': ['10:00', '12:00', '14:00', '16:00'],
        'arrival_time': ['08:00', '14:00', '18:00', '22:00']}

# Create the DataFrame
df = pd.DataFrame(data)

# Set hierarchical index
df.set_index(['source', 'destination'], inplace=True)

# Print the DataFrame
print(df)

                     flight_no flight_name departure_time arrival_time
source  destination                                                   
Delhi   Chennai            121    Emirates          10:00        08:00
Mumbai  Bangalore          122      Indigo          12:00        14:00
Kolkata Hyderabad          123     Vistara          14:00        18:00
Chennai Mumbai             124   Air india          16:00        22:00
